# PostgreSQL
#   gem install pg
#
#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: help_find_back_development                     #insert the name of your app instead of "sample"
test:
  <<: *default
  database: help_find_back_test                #insert the name of your app instead of "sample"
production:
  <<: *default
  url: <%= Rails.application.credentials.elephant_sql_id %>
  sslmode: "require"
